### PR TITLE
do not regenerate lock files

### PR DESCRIPTION
**Pull request by hpouillot**
speedup installation by not generating lock files

### CODE REVIEW

**Review by deltheil — APPROVED** [review]

**Comment by catwell** [comment]
I think this won't work w/o `--no-dev` since we don't commit the dev lockfile, you either need both or none.

**Review by catwell — CHANGES_REQUESTED** [review]
I think this won't work w/o --no-dev since we don't commit the dev lockfile, you either need both or none.

**Comment by hpouillot** [comment]
Indeed, didn't know the dev lockfile wasn't part of the repo.

**Comment by catwell** [comment]
@limiteinductive @deltheil WDYT?

In Disciple or PHX I don't do it because things like pyright are not dev deps so it is useless (and I can use dev to prototype stuff locally). But here if we want to use the dev deps and not generate the lock we'll have to do this.

On the other hand if we do this we need to remember to update the lock manually, we won't detect breaking changes in deps as frequently.

**Pull request closed without merging**
